In [1]:
import numpy as np
u = np.random.rand(2)
v = np.random.rand(2)

In [6]:
uv = np.column_stack([u,v])

In [7]:
uv.sort()

In [8]:
uv

array([[0.09691684, 0.79168604],
       [0.40106955, 0.44426852]])

In [9]:
u

array([0.79168604, 0.40106955])

In [14]:
r = (uv > 0.1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
r

array([[False,  True],
       [ True,  True]])

In [15]:
s = (uv < 0.7)

In [16]:
r*s

array([[False, False],
       [ True,  True]])

In [17]:
uv[r*s]

array([0.40106955, 0.44426852])

In [18]:
(r*s).nonzero()

(array([1, 1]), array([0, 1]))